### ISSUE TITLE
Z Open Editor does not activate when Zowe profiles settings are incorrect

### ISSUE THREAD

**Issue by ktenberg** [IBM/zopeneditor-about#110]
I would first like to thank, in advance, anyone willing to help with this issue.   
 
Environment

- Z Open Editor version: v1.1.3
- Visual Studio Code v1.52.1
- Extensions 
- - IBM DB2 for z/OS Developer Extension
- - Overtype
- - Zowe

- Operating System - Windows 10 Enterprise
- java version "1.8.0_271"
- Java(TM) SE Runtime Environment (build 1.8.0_271-b09)
- Java HotSpot(TM) 64-Bit Server VM (build 25.271-b09, mixed mode)
- Zowe CLI version: 6.25.0
- Node.js version: v14.15.4

Problem Description

A few days most features stopped working (all were initially working)

- References (Find All,  Peek, etc.)
- Outline
- Copybook lookup
- Tab stops - If I use the tab key I get "command 'zopeneditor.tab' not found"

**Comment by ktenberg** [comment]
I tired IBM Z Open Editor: Pause the Assembler Language Server.   This produced the following response
Command 'IBM Z Open Editor: Pause the Assembler Language Server' resulted in an error (command 'zlang.stopHLASMLsp' not found)

**Comment by ktenberg** [comment]
Remedies I have tried

1. disable and re-enable Z Open Editor
2. uninstall and re-install  Z Open Editor
3. uninstall and re-install VS Code

**Comment by gplambert** [comment]
@ktenberg Thanks for filing this issue, we will take a look.

**Comment by ktenberg** [comment]
Thank you!

**Comment by phaumer** [comment]
@ktenberg did you check the log files following these instructions? Could you attach it here? https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html#finding-versions-of-all-vs-code-extensions-installed

It sounds like a problem with activation. This can already happen if Zowe Explorer does not activate, which can happen with invalid user settings unfortunately, which is a know issue we want to fix.

**Comment by ktenberg** [comment]
changed setting.json ->      "zopeneditor.logger": "DEBUG",
Terminal output 

[2021-01-11 9:26:41.135 - DEBUG] ** Initialized IBM Z Open Editor logger on level "DEBUG". Welcome! **
[2021-01-11 9:26:41.137 - DEBUG] ** The log file is available at "c:\Users\ktenberg\AppData\Roaming\Code\logs\20210111T092634\exthost1\IBM.zopeneditor\zopeneditor-20210111-92641.log". **
[2021-01-11 9:26:41.139 - DEBUG] ** Z Open Editor Activation: Zowe CLI Secure Credentials Plugin is active. Will initialize Z Open Editor to utilize it. **
[2021-01-11 9:26:41.143 - DEBUG] ** Z Open Editor Activation: Zowe CLI Secure Credentials Plugin successfully activated for Z Open Editor. **

Do you want the log file contents?

**Comment by phaumer** [comment]
@ktenberg is this all the information that is in the file? If no, then it would be good to see the entire thing to trace along.

**Comment by ktenberg** [comment]
Hi Peter,

The entire log is attached…

I did notice the following therein…

[2021-01-11 09:26:41.382] [exthost] [error] Activating extension IBM.zopeneditor failed due to an error:
[2021-01-11 09:26:41.382] [exthost] [error] Error: Your default profile named db2a does not exist for type zosmf.
To change your default profile, run "undefined profiles set-default zosmf <profileName>".
                at d.<anonymous> (c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:211:166389)
                at Generator.next (<anonymous>)
                at c:\Users

I have the following in my settings.json…
                "zopeneditor.zowe": {"defaultCliProfile": "db2b"},       I have tried upper case for the profile name because of the result below

When I issue the zowe command zowe profiles list zosmf-profiles..

C:\dev\ccm\wa\adu\1122\adu\code\asm>zowe profiles list zosmf-profiles
DB2B

C:\dev\ccm\wa\adu\1122\adu\code\asm>

**Comment by ktenberg** [comment]
Not sure how to attach a file.
Entire log file follows
[2021-01-11 09:57:28.937] [exthost] [info] extension host started
[2021-01-11 09:57:29.033] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication {"startup":false,"extensionId":{"value":"vscode.microsoft-authentication","_lower":"vscode.microsoft-authentication"},"activationEvent":"onAuthenticationRequest:microsoft"}
[2021-01-11 09:57:29.034] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-01-11 09:57:29.050] [exthost] [info] ExtensionService#_doActivateExtension vscode.configuration-editing {"startup":false,"extensionId":{"value":"vscode.configuration-editing","_lower":"vscode.configuration-editing"},"activationEvent":"onLanguage:jsonc"}
[2021-01-11 09:57:29.050] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/configuration-editing/dist/configurationEditingMain
[2021-01-11 09:57:29.061] [exthost] [info] ExtensionService#_doActivateExtension vscode.json-language-features {"startup":false,"extensionId":{"value":"vscode.json-language-features","_lower":"vscode.json-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-01-11 09:57:29.061] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/json-language-features/client/dist/node/jsonClientMain
[2021-01-11 09:57:29.080] [exthost] [info] ExtensionService#_doActivateExtension vscode.typescript-language-features {"startup":false,"extensionId":{"value":"vscode.typescript-language-features","_lower":"vscode.typescript-language-features"},"activationEvent":"onLanguage:jsonc"}
[2021-01-11 09:57:29.080] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/typescript-language-features/dist/extension
[2021-01-11 09:57:29.098] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch {"startup":true,"extensionId":{"value":"vscode.debug-auto-launch","_lower":"vscode.debug-auto-launch"},"activationEvent":"*"}
[2021-01-11 09:57:29.098] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-01-11 09:57:29.105] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet {"startup":true,"extensionId":{"value":"vscode.emmet","_lower":"vscode.emmet"},"activationEvent":"*"}
[2021-01-11 09:57:29.106] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-01-11 09:57:29.121] [exthost] [info] ExtensionService#_doActivateExtension vscode.git {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-01-11 09:57:29.121] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/git/dist/main
[2021-01-11 09:57:29.144] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict {"startup":true,"extensionId":{"value":"vscode.merge-conflict","_lower":"vscode.merge-conflict"},"activationEvent":"*"}
[2021-01-11 09:57:29.145] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-01-11 09:57:29.149] [exthost] [info] ExtensionService#_doActivateExtension vscode.search-result {"startup":true,"extensionId":{"value":"vscode.search-result","_lower":"vscode.search-result"},"activationEvent":"*"}
[2021-01-11 09:57:29.149] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/search-result/dist/extension.js
[2021-01-11 09:57:29.153] [exthost] [info] ExtensionService#_doActivateExtension IBM.db2forzosdeveloperextension {"startup":true,"extensionId":{"value":"IBM.db2forzosdeveloperextension","_lower":"ibm.db2forzosdeveloperextension"},"activationEvent":"*"}
[2021-01-11 09:57:29.153] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/.vscode/extensions/ibm.db2forzosdeveloperextension-0.5.6/dist/client
[2021-01-11 09:57:29.177] [exthost] [info] ExtensionService#_doActivateExtension Zowe.vscode-extension-for-zowe {"startup":true,"extensionId":{"value":"Zowe.vscode-extension-for-zowe","_lower":"zowe.vscode-extension-for-zowe"},"activationEvent":"*"}
[2021-01-11 09:57:29.177] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/.vscode/extensions/zowe.vscode-extension-for-zowe-1.11.1/out/src/extension
[2021-01-11 09:57:29.765] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug {"startup":false,"extensionId":{"value":"ms-vscode.js-debug","_lower":"ms-vscode.js-debug"},"activationEvent":"onCommand:extension.js-debug.clearAutoAttachVariables"}
[2021-01-11 09:57:29.765] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-01-11 09:57:29.944] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication {"startup":false,"extensionId":{"value":"vscode.github-authentication","_lower":"vscode.github-authentication"},"activationEvent":"onAuthenticationRequest:github"}
[2021-01-11 09:57:29.944] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/github-authentication/dist/extension.js
[2021-01-11 09:57:30.146] [exthost] [info] ExtensionService#_doActivateExtension vscode.github {"startup":true,"extensionId":{"value":"vscode.github","_lower":"vscode.github"},"activationEvent":"*"}
[2021-01-11 09:57:30.146] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/AppData/Local/Microsoft/Microsoft VS Code/resources/app/extensions/github/dist/extension.js
[2021-01-11 09:57:30.153] [exthost] [info] ExtensionService#_doActivateExtension IBM.zopeneditor {"startup":true,"extensionId":{"value":"IBM.zopeneditor","_lower":"ibm.zopeneditor"},"activationEvent":"*"}
[2021-01-11 09:57:30.154] [exthost] [info] ExtensionService#loadCommonJSModule file:///c:/Users/ktenberg/.vscode/extensions/ibm.zopeneditor-1.1.3/dist/extension
[2021-01-11 09:57:30.471] [exthost] [error] Activating extension IBM.zopeneditor failed due to an error:
[2021-01-11 09:57:30.471] [exthost] [error] Error: Your default profile named db2a does not exist for type zosmf.
To change your default profile, run "undefined profiles set-default zosmf <profileName>".
	at d.<anonymous> (c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:211:166389)
	at Generator.next (<anonymous>)
	at c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:211:160674
	at new Promise (<anonymous>)
	at r (c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:211:160419)
	at d.load (c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:211:165426)
	at d.<anonymous> (c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:77:268138)
	at Generator.next (<anonymous>)
	at o (c:\Users\ktenberg\.vscode\extensions\ibm.zopeneditor-1.1.3\dist\extension.js:77:266312)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)
[2021-01-11 09:57:30.471] [exthost] [info] eager extensions activated

**Comment by phaumer** [comment]
Thanks. Although this is from a different log file (extension host not Z Open Editor) it gives us the information we need. You need to fix your Zowe CLI profiles. You definitely need to be consistent with the cases. They are located in ~/.zowe/profiles/zosmf. 

I will keep this issue open for us to investigate why activation fails because of this setting. That should not happen.

**Comment by ktenberg** [comment]
Okay.. so what do I have to do to fix my Zowe CLI profiles?

**Comment by phaumer** [comment]
You need to look at your user setting `"zopeneditor.zowe": {"defaultCliProfile": "db2b"},` and check that the profile is a valid profile name in the right casing. Also I see in the error message `db2a` and you show this example with `db2b`.  If you only have one profile anyway then you can even remove this setting. It is meant for the use that that you do not want to use your default profile, i.e. the default used by Zowe CLI.

**Comment by ktenberg** [comment]
I got the extension to work by creating a new Zowe CLI profile  
changed settings.json --->  "zopeneditor.zowe": {"defaultCliProfile": "db2a"},

DDEBUG logger output is complete now...   Thanks Peter !!

[2021-01-11 12:15:42.602 - DEBUG] ** Initialized IBM Z Open Editor logger on level "DEBUG". Welcome! **
[2021-01-11 12:15:42.604 - DEBUG] ** The log file is available at "c:\Users\ktenberg\AppData\Roaming\Code\logs\20210111T121535\exthost1\IBM.zopeneditor\zopeneditor-20210111-121542.log". **
[2021-01-11 12:15:42.606 - DEBUG] ** Z Open Editor Activation: Zowe CLI Secure Credentials Plugin is active. Will initialize Z Open Editor to utilize it. **
[2021-01-11 12:15:42.610 - DEBUG] ** Z Open Editor Activation: Zowe CLI Secure Credentials Plugin successfully activated for Z Open Editor. **
[2021-01-11 12:15:43.556 - INFO] ** Zowe Explorer was modified for IBM Remote System Explorer API (RSE API) support by IBM Z Open Editor. **
[2021-01-11 12:15:44.99 - DEBUG] ** JavaFinder: Used the "zopeneditor.JAVA_HOME" user setting to locate Java. **
[2021-01-11 12:15:44.108 - DEBUG] ** Z Open Editor environment summary:
- Z Open Editor version: 1.1.3
- Editor platform: Visual Studio Code
- Editor platform version: 1.52.1
- Required minimal editor platform version: ^1.44.0
- Editor installation root directory: c:\Users\ktenberg\AppData\Local\Microsoft\Microsoft VS Code\resources\app
- Editor installation id: 60c996423c869f575fa4dd8886b167f8e6525788fbf5d7c1ffba8b0a0d0ed9ce
- Is a valid Java configured: true
  - Java: C:/Program Files/Java/jre1.8.0_271\bin\java.exe
  - Java memory allocation: 512
- Key user settings:
  - Unreachable Code enabled: true
  - ZAPP files enabled: true
  - ZAPP schema used: file:///c%3A/Users/ktenberg/.vscode/extensions/ibm.zopeneditor-1.1.3/resources/zapp-schema-0.0.1.json
  - IBM User Build enabled: true
  - Zowe CLI Secure Credentials enabled: true
  - Zowe CLI files profile user setting: db2a
  - Zowe CLI files profile used: db2a
  - Zowe CLI SSH profile user setting: Not defined.
  - Zowe CLI SSH profile used: No profile found.
  - Zowe Temp-Dir value: Not defined.
  - COBOL Property Groups defined: 
  - COBOL include file extensions: .cpy,.copybook,.copy,.cobcopy
  - PL/I Property Groups defined: 
  - PL/I include file extensions: .inc,.include,.plinc,.pcx,.pci
  - HLASM Property Groups defined: local-macros
  - HLASM include file extensions: .s,.assemble,.asm,.hlasm,.hla,.mac
  - VS Code Files Assocications: *.COBOL*:cobol,*.COB*:cobol,*.COBCOPY*:cobol,*.COPYBOOK*:cobol,*.COPY*:cobol,*.PL1*:pl1,*.PLI*:pl1,*.INC*:pl1,*.INCLUDE*:pl1,*.JCL*:jcl,*.ASM*:hlasm,*.ASSEMBLE*:hlasm,*.HLASM*:hlasm,*.HLA*:hlasm,*.MAC*:hlasm,*.mac:hlasm
- Zowe Explorer VS Code Extension version: 1.11.1
  - Successfully activated: true
  - Installation path: c:\Users\ktenberg\.vscode\extensions\zowe.vscode-extension-for-zowe-1.11.1

**Comment by phaumer** [comment]
@ktenberg great new. We will be working on making this more robust in the future and leave this item open as a reminder.

**Comment by phaumer** [comment]
@ktenberg fixed in v1.2.0. Let us know if you still have issues or suggestions.
