### ISSUE TITLE
HEX 

### ISSUE THREAD

**Issue by davidkcoblentz** [IBM/zopeneditor-about#183]
## Description of the enhancement requested

- I would like to see..

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] HEX  (Issue #183)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by FALLAI-Denis** [comment]
Hi,

Personally, I think the use of hex characters directly in the sources should be avoided.
This already poses problems on the mainframe if the codepages are incorrectly declared. But things are worse with the EBCIDIC / UTF8 (or ASCII) conversions that occur for work in VS Code.
After conversion, the characters lose all meaning.

VS Code, and Z Open Editor, is a source code editor (source programs editor). It is not a data file editor. The files handled must only use displayable characters. 

You must use the X'nn 'syntax in COBOL, or equivalent in other languages, to introduce hex values in the source codes. 

Otherwise to see the values of hexa or non-displayable characters in VS Code, see the extension [Gremlins tracker for Visual Studio Code](https://marketplace.visualstudio.com/items?itemName=nhoizey.gremlins).

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro. Ich kehre zurück am  06.12.2021.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] HEX / Text Source Code Editing (Issue #183)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by phaumer** [comment]
Yes, on the VS Code side we are working with UTF-8 only. Conversions are handled for us by z/OSMF or RSE API. Microsoft has a [Hex extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.hexeditor) as well, but this will not help much here I guess. 

I would not think that we would try this any time soon for Z Open Editor. As you might know we are also partnering with other companies for data editing for our other editors, but unfortunately VS Code support is behind.

**Comment by davidkcoblentz** [comment]
Thank you both so much for your quick answers!  I see your point that it is a source editor.   I am still checking out why the original developers put non-displayable bytes of data in the MFS.  I will document it here if I come to understand why.  I am suspecting MFS 3270 attribute bytes but am still checking.

I also noticed when I brought my REXX source code into VS Code from the mainframe that the '|' (vertical bar), used as the logical OR operator, is not translating properly so it shows as a non-displayable character. I am also investigating to see if I should be using a different code-page other than  **English 037 to ASCII 437** when downloading from the mainframe.
![image](https://user-images.githubusercontent.com/80063515/142082896-5b43df44-4654-4a08-8dac-1ca05890cd49.png)

**Comment by FALLAI-Denis** [comment]
Hi,

For EBCDIC / UTF8 character conversions, see
[The ebcdic x'CA 'character (IBM-1147) is missing after transfer with ZOWE Explorer (with encoding 1147) / soft hyphen x'AD' not rendered by Chromium](https://github.com/zowe/vscode-extension-for-zowe/issues/923)

**Comment by phaumer** [comment]
For RSE API users there is documentation on conversion options here: https://ibm.github.io/zopeneditor-about/Docs/mvs_encoding.html  If you find any conversion problems with RSE let us know here as well.

**Comment by davidkcoblentz** [comment]
Thank you!  I just realized you had questions above that I didn't answer.
Questions:
There seems to be another problem with your configuration.
    Is the encoding conversion correctly set at Zowe CLI? **We are in the process of configuring zOSMF and getting ZOWE connectivity. I am currently downloading each source member with my 3270 Terminal emulator Aviva.  I will address this when we get zOSMF / Zowe configured**
    Is the correct encoding declared in VS Code?  **Same as above**
    Auto detection problem of the encoding in VS Code? **Same as above**
    Try "reopen with encoding" in VS Code. # **Same as above**

**Comment by FALLAI-Denis** [comment]
Hi @davidkcoblentz 

This is probably the origin of the problem.
When you download files, be sure to convert encoding from the ccsid used for your mainframe (the ccsid defined in your 3270 emulator) to UTF8 (without bom). 

If you use "ind$file" look at parameters of your emulator, (ftp should be a better solution). 

I think you can use Zowe CLI "zftp" without z/osmf. Otherwise use client ftp of your workstation.

**Comment by davidkcoblentz** [comment]
Great! Thanks, I will try the CLI to see.

Thank you,
***@***.***

**Comment by FALLAI-Denis** [comment]
PS : 

If you want to do an FTP transfer directly with z/OS, you may encounter problems because the z/OS FTP server does not accept to switch from single-byte encoding (IBM-037) to multibyte encoding (UTF-8 / IBM-1208).

One solution would be to transfer via FTP from IBM-037 to IBM-1252, then apply a local transformation to UTF8, for example by opening the transferred file in VS Code in Windows-1252 and then saving it in UTF-8.

**Comment by FALLAI-Denis** [comment]
Hi @davidkcoblentz, @phaumer 

I remain convinced that we cannot transfer a file containing non-displayable characters (binary data or packaged decimal) and apply an encoding translation to it, (go from EBCDIC to UTF8 and vice versa).

Nevertheless, the editing of (small) data files remains a common need, (for large data files it is better to turn to a specific tool which is no longer direct file editing).

For this, I made two proposals for the development of the Zowe Explorer application, which you could consider and support by voting:
- [Not all mvs data sets necessarily use the same ccsid #1589](https://github.com/zowe/vscode-extension-for-zowe/issues/1589)
- [Editor in hexadecimal dump mode with EBCDIC interpretation #1590](https://github.com/zowe/vscode-extension-for-zowe/issues/1590)

Thanks.

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] HEX / Text Source Code Editing (Issue #183)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by davidkcoblentz** [comment]
Thank you! Great ideas! I up-voted both of these.

Thank you,
***@***.***

**Comment by benjamin-t-santos** [comment]
Hello. We have released a new advanced capability in 6.6.0 to allow users to view and edit the hexadecimal values for the bytes of sequential data sets and PDS members: the [Line Hex Editor](https://ibm.github.io/zopeneditor-about/Docs/advanced_line_hex_editor.html). Check out linked docs to see how it works, and we'd love to hear any feedback you have. 

<img width="1300" height="844" alt="Image" src="https://github.com/user-attachments/assets/363c7b96-a7b5-4425-89a0-311dad121674" />

**Comment by FALLAI-Denis** [comment]
Hi,

What are the access requirements for the HexEdit function?
I don't have this option in my menus, despite having an IDzEE license.

<img width="518" height="90" alt="Image" src="https://github.com/user-attachments/assets/9250555a-2ef4-49d7-9560-5535b32bf71a" />

---

I understand: this function only applies to "remote" files opened on z/OS using Zowe Explorer...
However, it would also be useful for local files, which would then be encoded in UTF-8, ISO-8859-x, or Windows-xxxx.

<img width="523" height="136" alt="Image" src="https://github.com/user-attachments/assets/08f9c780-1b36-4bc8-93bc-393f76042361" />

--- 

Oups...

<img width="1250" height="124" alt="Image" src="https://github.com/user-attachments/assets/3e51d06a-b4a0-4f0e-ae85-1f4dcf8328e8" />

And provided that a RSE API connection is used, and not a z/OSMF connection...
😭

**Comment by benjamin-t-santos** [comment]
Hi @FALLAI-Denis, yes, it is currently only for remote files.
My apologies that you are seeing an issue so early on. I'd like to investigate the error you are seeing by reading your Z Open Editor logs on the DEBUG level. If you'd be willing to run the **IBM Z Open Editor: Export Support Files** command and share the .zip, that would be helpful. If you do not want to share all zipped files, the Z Open Editor and Language Server logs should suffice. 
If you could share any details about the member/seq data set attributes or the specific line you are trying to open, please do so.

**Comment by FALLAI-Denis** [comment]
Hi @benjamin-t-santos, 

<img width="370" height="471" alt="Image" src="https://github.com/user-attachments/assets/d26ea48c-d5bb-4347-bad0-f9a4bad2efcf" />

<img width="696" height="85" alt="Image" src="https://github.com/user-attachments/assets/3ae6e818-3fdb-4f26-a4d2-13bb2821219a" />

<img width="700" height="35" alt="Image" src="https://github.com/user-attachments/assets/522d6a0b-8328-4450-af4b-7651a607a67c" />

Working with z/OSMF profile, with a "projet zowe.config.json" inside Workspace.

<img width="603" height="358" alt="Image" src="https://github.com/user-attachments/assets/c530aa67-78be-4848-a0bb-cb2a9554fe2f" />

```
2026-06-22T17:43:43.507+02:00 INFO : CRRZG5563I Loading data set "J070188.PUBLIC.COBOL.SRCELIB(VALMAIL2)" as binary for hex editor using profile "GMVS".
2026-06-22T17:43:43.742+02:00 INFO : CRRZG5564I Successfully downloaded data set "J070188.PUBLIC.COBOL.SRCELIB(VALMAIL2)" (17120 bytes) with code page "1147".
2026-06-22T17:43:43.749+02:00 DEBUG: Hex editor document created successfully for line 48
2026-06-22T17:43:43.760+02:00 ERROR: CRRZG5562E Failed to generate character-byte mappings using code page 1147: "Unexpected error: Cannot invoke \"com.ibm.icu.charset.CharsetEncoderICU.charset()\" because \"this.encoder\" is null".
```

```
!ENTRY com.ibm.wazi.lsp.cobol.core 4 0 2026-06-22 17:43:43.758
!MESSAGE Unexpected error in cobol.get.char.byte.mappings
!STACK 0
java.lang.NullPointerException: Cannot invoke "com.ibm.icu.charset.CharsetEncoderICU.charset()" because "this.encoder" is null
	at com.ibm.systemz.common.editor.cache.CharsetEncoding.decodeByteOffsetToCharOffset(CharsetEncoding.java:489)
	at com.ibm.systemz.common.editor.cache.ByteCharMappings.buildByteToCharIndex(ByteCharMappings.java:127)
	at com.ibm.systemz.common.editor.cache.ByteCharMappings.createMappings(ByteCharMappings.java:89)
	at com.ibm.systemz.common.editor.cache.ByteCharMappings.create(ByteCharMappings.java:50)
	at com.ibm.wazi.lsp.common.core.commands.ConversionUtils.getCharByteMappings(ConversionUtils.java:112)
	at com.ibm.wazi.lsp.common.core.commands.AbstractGetCharByteMappingsCommand.execCommand(AbstractGetCharByteMappingsCommand.java:42)
	at com.ibm.wazi.lsp.cobol.core.commands.GetCharByteMappings.execCommand(GetCharByteMappings.java:37)
	at com.ibm.wazi.lsp.cobol.core.commands.GetCharByteMappings.execCommand(GetCharByteMappings.java:1)
	at com.ibm.wazi.lsp.cobol.core.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:29)
	at com.ibm.wazi.lsp.cobol.core.CobolLanguageServer.lambda$11(CobolLanguageServer.java:322)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

Support files:
[z_open_editor_logs_2026-06-22T15-44-08-813Z.zip](https://github.com/user-attachments/files/29213379/z_open_editor_logs_2026-06-22T15-44-08-813Z.zip)

**Comment by benjamin-t-santos** [comment]
Thank you @FALLAI-Denis.
I suspect that our language servers are not recognizing `1147` as an alias for `IBM-1147`. Can you update the `encoding` property in your Zowe profile to `IBM-1147`, reload VS Code, and try the Line Hex Editor again?
When I use `1147`, I see the same error as you. After changing to `"encoding" : "IBM-1147"` in my profile and reloading VS Code, the Line Hex Editor loads.

**Comment by FALLAI-Denis** [comment]
Hi @benjamin-t-santos 

Good point!

<img width="545" height="353" alt="Image" src="https://github.com/user-attachments/assets/7dd921b6-385e-4220-b622-0e22ed158916" />

<img width="896" height="192" alt="Image" src="https://github.com/user-attachments/assets/ba0f00ac-8725-48ac-aa9a-946df436291c" />

But we have always used "1147" and not "IBM-1147" in all our profiles...
