### ISSUE TITLE
Error with bool Variable in PLI Code

### ISSUE THREAD

**Issue by kraabrsg** [IBM/zopeneditor-about#194]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.60.1
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Win 10 Enterprise 10.0.19042 Build 19042
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
 java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:  6.32.1
  - Node.js version: V14.15.3
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

![grafik](https://user-images.githubusercontent.com/86772851/142989382-02b289e2-2c68-4e99-aacb-56ee1f473dcb.png)
![grafik](https://user-images.githubusercontent.com/86772851/142989445-d1fb9aab-4d39-48d0-b137-8b3a196e4e0f.png)

![grafik](https://user-images.githubusercontent.com/86772851/142989407-1f77302f-e277-4cd1-8728-7e26c60bb61a.png)

### Observed behavior

Error Message pops up

### Expected behavior

No Error Message

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
[IBM/zopeneditor-about] Error with bool Variable in PLI Code (Issue #194)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by gplambert** [comment]
@kraabrsg Is it possible to attach a sample, non-proprietary example to this issue that I could use to research this issue?

**Comment by kkrein** [comment]
Ich bin derzeit nicht im Büro.
Während meiner Abwesenheit bitte bei Postkorb SCM-Admin melden!

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [IBM/zopeneditor-about] Error with bool Variable in PLI Code (Issue
#194)

____________________________________________________________________________________________
Gesendet (c) GRZ/RSG Linz 2021 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by kraabrsg** [comment]
@gplambert
I tried to make a little dummy programm to showcase the error from the screenshot, but i can't reproduce it(i don't understand why).

The weird thing is, that in the source code i have some preproc statements, which leads normally to various parsing errors.
But that's not the case anymore, and only from this source code ...???

Some strange coloring occurs(gone after restart, not reproducable):
![grafik](https://user-images.githubusercontent.com/86772851/144057481-96fe1b49-1dbb-45b6-be37-e8c42780f568.png)


 The only thing i found:
C:\Users\xxxxxx\AppData\Roaming\VSCodium\logs\20211130T131644\exthost1\exthost.log
(see also better formatted in the attached file)
[extensionslog.txt](https://github.com/IBM/zopeneditor-about/files/7626130/extensionslog.txt)

`
[2021-11-30 13:50:05.830] [exthost] [warning] IBM.zopeneditor - Code actions of kind 'quickfix 'requested but returned code action is of kind ''. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
[2021-11-30 13:50:06.421] [exthost] [warning] IBM.zopeneditor - Code actions of kind 'quickfix 'requested but returned code action is of kind ''. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
[2021-11-30 13:52:17.752] [exthost] [error] [IBM.zopeneditor] provider FAILED
[2021-11-30 13:52:17.752] [exthost] [error] Error: Illegal argument: range
	at T (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new be (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:37684)
	at new be (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:17480)
	at new i (c:\Users\XXXXX\.vscode-oss\extensions\ibm.zopeneditor-1.4.1\dist\extension.js:8:1526089)
	at B (c:\Users\XXXXX\.vscode-oss\extensions\ibm.zopeneditor-1.4.1\dist\extension.js:8:1521731)
	at Array.map (<anonymous>)
	at asDocumentLinks (c:\Users\XXXXX\.vscode-oss\extensions\ibm.zopeneditor-1.4.1\dist\extension.js:8:1525514)
	at async Q.provideLinks (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:181601)
[2021-11-30 13:52:19.773] [exthost] [warning] IBM.zopeneditor - Code actions of kind 'quickfix 'requested but returned code action is of kind ''. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
[2021-11-30 14:17:57.943] [exthost] [error] [IBM.zopeneditor] provider FAILED
[2021-11-30 14:17:57.943] [exthost] [error] Error: Illegal argument: range
	at T (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:5:1232)
	at new be (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:37684)
	at new be (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:87:17480)
	at new i (c:\Users\XXXXX\.vscode-oss\extensions\ibm.zopeneditor-1.4.1\dist\extension.js:8:1526089)
	at B (c:\Users\XXXXX\.vscode-oss\extensions\ibm.zopeneditor-1.4.1\dist\extension.js:8:1521731)
	at Array.map (<anonymous>)
	at asDocumentLinks (c:\Users\XXXXX\.vscode-oss\extensions\ibm.zopeneditor-1.4.1\dist\extension.js:8:1525514)
	at async Q.provideLinks (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:94:181601)
[2021-11-30 14:18:00.731] [exthost] [warning] IBM.zopeneditor - Code actions of kind 'quickfix 'requested but returned code action is of kind ''. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
[2021-11-30 14:18:01.844] [exthost] [warning] IBM.zopeneditor - Code actions of kind 'quickfix 'requested but returned code action is of kind ''. Code action will be dropped. Please check 'CodeActionContext.only' to only return requested code actions.
[2021-11-30 14:23:57.912] [exthost] [info] extension host terminating: renderer closed the socket
[2021-11-30 14:23:58.162] [exthost] [error] TypeError: Cannot read property 'dispose' of undefined
	at ShowHelpFeature.dispose (c:\Users\XXXXX\.vscode-oss\extensions\ms-vscode.powershell-2021.8.2\out\src\features\ShowHelp.js:30:32)
	at c:\Users\XXXXX\.vscode-oss\extensions\ms-vscode.powershell-2021.8.2\out\src\main.js:172:32
	at Array.forEach (<anonymous>)
	at Object.deactivate (c:\Users\XXXXX\.vscode-oss\extensions\ms-vscode.powershell-2021.8.2\out\src\main.js:171:29)
	at v._deactivate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:11277)
	at c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:9991
	at Array.map (<anonymous>)
	at v.deactivateAll (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:99:9979)
	at E.terminate (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:723)
	at a (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:32208)
	at Socket.<anonymous> (c:\Program Files\VSCodium\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:113:29858)
	at Socket.emit (events.js:327:22)
	at Pipe.<anonymous> (net.js:673:12)
`

hope this helps...

**Comment by gplambert** [comment]
@kraabrsg - thanks, our developers will look into this

**Comment by phaumer** [comment]
@kraabrsg for this issue we would be interested in producing the quickfix errors you are showing above. Can you describe how to reproduce these? Are the special syntax errors on which you clicked the Quick Fix option when this error appears?

**Comment by kraabrsg** [comment]
Hi @phaumer as stated in my previous post, i was not able to reproduce that(after a restart). As far as i remember this pops up(while typing), and was no Quick Fix option. Thanks!

**Comment by phaumer** [comment]
@kraabrsg thanks. I am closing this one for now, but we try to keep an eye on every warning we see anyway. Let's reopen here if we can reproduce it.
