### ISSUE TITLE
Request textDocument/codeAction failed. Message: Internal error.   Code: -32603. Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by yifatoren** [IBM/zopeneditor-about#230]
Hi,

I'm trying out a new Build task with problemMatcher defined so I can easily trace HLASM compile errors. 

When clicking on the Problem (see image) to see the problematic source code line, which is displayed correctly - I receive the following java exception from the HLASM Language Server:

[Error - 3:14:36 PM] Request textDocument/codeAction failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:618)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.NullPointerException
	at com.ibm.wazi.lsp.hlasm.core.handlers.CodeActionFactory.of(CodeActionFactory.java:60)
	at com.ibm.wazi.lsp.hlasm.core.handlers.CodeActionHandler.getCodeAction(CodeActionHandler.java:29)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer.lambda$4(HLASMLanguageServer.java:189)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer$$Lambda$35/0000000000000000.apply(Unknown Source)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer.lambda$9(HLASMLanguageServer.java:222)
	at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer$$Lambda$34/0000000000000000.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	... 6 more

![image](https://user-images.githubusercontent.com/52377837/160399721-259638a1-4f72-47c4-845d-6ca6b5365d0e.png)

Please let me know if you need any more information from me.

Thanks,
Yifat Oren

**Comment by sdaimwood** [comment]
Hi Yifat, thanks for reporting this. Just a couple questions to clarify the environment you're using when seeing this:

- Which operating system do you have VS Code running in? 
- Which version of Z Open Editor are you using?
- Are you able to reproduce the exception consistently when you click the item in the Problems view?

**Comment by yifatoren** [comment]
Hey Saile,

1. Win10 Final Release Q2 FY19
2. v2.0.0 under VSCode 1.65.2
3. Definitely. Same exception with every double-click on a Problem item. 

Please let me know if I can get you any logs/traces/definitions/whatever.

Thanks!
Yifat

**Comment by sdaimwood** [comment]
Hi @yifatoren, wanted to follow up to see if you are still experiencing this issue after the release of 2.0.2? 

If you are and if possible, could you pass along the relevant sections of your "tasks.json" that you have your problemMatcher defined in and/or the build script you are using? This will better help us figure out why these codes aren't being passed to the language server correctly. 

Thanks again.

**Comment by yifatoren** [comment]
Hi @sdaimwood,

Yes, the issue still exists in 2.0.2. 

My tasks.json snippet:

{
            "label": "asm",
            "type": "shell",
            "command": "zowe",
            "args": [
                "zos-uss",
                "issue",
                "command",
                "as -ILIB.MAC:LIB1.MAC -o OBJECT.o \"\"//'${fileBasename}'\"\""
            ],
            "problemMatcher": {
                "owner": "zowe",
                "fileLocation": [
                    "relative",
                    "${workspaceFolder}/temp/_D_/sysp"
                ],
                "pattern": [
                    {
                        "regexp": "^\\s(ASMA.+(E|W|I|S)[\\s.+)$](file:///)",
                        "severity": 2,
                        "message": 1
                    },
                    {
                        "regexp": "^\\sASMA435I(.+)[\\s(\\d+)\\s(.+)\\s(.+)\\s(.+)\\s(.+)\\s(.+)](file:///d+)/s(.+)/s(.+)/s(.+)/s(.+)/s(.+))",
                        "file": 4,
                        "line": 2
                    }
                ]
            }
        },

Thanks for looking into this,
Yifat

**Comment by sdaimwood** [comment]
Hi @yifatoren, has this issue been fixed with the release of 2.1.0?

**Comment by yifatoren** [comment]
Hi @sdaimwood - I'm happy to report the issue was indeed fixed. 

Thank you very much!
