### ISSUE TITLE
Error when opening copybook include from PLI editor.

### ISSUE THREAD

**Issue by nk2164** [IBM/zopeneditor-about#277]
## Development environment used

- Z Open Editor version:
- Editor Platform
  - [x] Visual Studio Code
  - [ ] Red Hat CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version:
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3):  Windows
- Java Version (when using VS Code or Theia, execute `java -version` and paste the details here):
java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b25)
Java HotSpot(TM) 64-Bit Server VM (build 25.341-b25, mixed mode)

- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version: v2.3.0
  - Node.js version: v17.8.0
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html) how to get them): yes/no

## Problem Description

Detailed steps for reproducing the problem:

1. First step

### Observed behavior
I tried to ctrl + click to browse an include PLI copybook in code. It opens the included copybook, but then i see a message box that error that the request failed. The output contains the following:

[Error - 8:15:15 PM] Request textDocument/foldingRange failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.NullPointerException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:284)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:291)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:629)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:468)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:300)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1078)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1714)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.NullPointerException
	at com.ibm.wazi.lsp.pli.core.handlers.FoldingRangeHandler.computeFoldingRanges(FoldingRangeHandler.java:42)
	at com.ibm.wazi.lsp.pli.core.PLILanguageServer.lambda$4(PLILanguageServer.java:199)
	at com.ibm.wazi.lsp.pli.core.PLILanguageServer$$Lambda$36/0x000000000747d310.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:627)
	... 6 more
-

### Expected behavior
I expected to see the included copybook member
-

**Comment by phaumer** [comment]
See more details in https://github.com/IBM/zopeneditor-about/issues/283
