### ISSUE TITLE
Connection disposed by Language server

### ISSUE THREAD

**Issue by YvesMichon** [IBM/zopeneditor-about#358]
## Development environment used

- Z Open Editor version: 3.2.2
- Editor Platform : Visual Studio Code
- Editor Platform Version: 1.80.2
- Operating System : Win10
- Java Version : 17.0.4.1
- Logs attached : yes

## Problem Description
[](url)
Hi
On a particular machine, we have errors when loading a Cobol program just after resolving COPY.
We see those message in Cobol Sever Language output : 

```
Connection to server got closed. Server will restart
...
Connection to server got closed. Server will not be restarted
```
And we have the error message in VSCode : 
`
The COBOL Laanguage Server crashed 5 times in the last 3 minutes. The server will not be restarted
`
We see the resolution of COPY (they'll be underlined with white line) and just after they are underlined by a red line.
We have set the DEBUG for logging for the plugin.
We've tried to upgrade memory allocation for the JVM to 1024 but same problem.
Tried also with 3.2.1 version.

[ibmzopeneditor.log](https://github.com/IBM/zopeneditor-about/files/12793350/ibmzopeneditor.log)
[serverLanguage.log](https://github.com/IBM/zopeneditor-about/files/12793357/serverLanguage.log)

**Comment by phaumer** [comment]
@YvesMichon could you check if v3.3.0 fixes your issue? If not please reopen.

**Comment by YvesMichon** [comment]
Hello @phaumer 
I tested version 3.3.0 on my computer and got messages very similar to those shown in the request.

Log of Cobol Language Server
`
[Error - 10:01:40] Request textDocument/documentLink failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\inemicy\.vscodeMoMaEQX\ibm.zopeneditor-3.3.0\dist\extension.js:8:1916445)
	at Object.dispose (c:\Users\inemicy\.vscodeMoMaEQX\ibm.zopeneditor-3.3.0\dist\extension.js:8:1980282)
	at c:\Users\inemicy\.vscodeMoMaEQX\ibm.zopeneditor-3.3.0\dist\extension.js:8:1976878
`
Log of IBM Z Open Editor
`
2023-10-27T10:01:59.315+02:00 INFO : The COBOL language server requested the include file "SNDATCT1", which was found and available as file "file:///c%3A/Users/inemicy/.vscodeMoMaEQX/ibm.zopeneditor-3.3.0/resources/temp/zopeneditor/_D_/zosmf/E%24DTA.%24RSRCTES.COPYSNP/SNDATCT1.cpy".
2023-10-27T10:02:02.004+02:00 WARN : The COBOL language server requested the include file "CAPUC1YI", which was not found. enforceCaseSensitiveIncludeFileNames was set to false. Check your Zowe CLI profile and property group settings and if you have not already done so, switch to the "DEBUG" log level for more information.
2023-10-27T10:02:02.704+02:00 WARN : The COBOL language server requested the include file "TBP9B11I", which was not found. enforceCaseSensitiveIncludeFileNames was set to false. Check your Zowe CLI profile and property group settings and if you have not already done so, switch to the "DEBUG" log level for more information.
2023-10-27T10:02:03.545+02:00 WARN : The COBOL language server requested the include file "TBP9B02I", which was not found. enforceCaseSensitiveIncludeFileNames was set to false. Check your Zowe CLI profile and property group settings and if you have not already done so, switch to the "DEBUG" log level for more information.
`

And this notification appears
![requelst failed](https://github.com/IBM/zopeneditor-about/assets/79926253/729ebb57-80e8-4049-aed6-b633de1cc1ae)

Sometimes we have also those messages but not each times
![temporary](https://github.com/IBM/zopeneditor-about/assets/79926253/240fe6d3-85a2-4822-99f9-770472c9da9c)

**Comment by YvesMichon** [comment]
Sorray I'm unable to reopen this issue. No button

**Comment by FALLAI-Denis** [comment]
Hi @YvesMichon , @phaumer 

Is it possible that problem is relative to use of « $ » character wich has a special meaning both on z/OS-USS and on Windows?

I am from same company as Yves. 
We use IBM-1147 encoding on z/OS (at 3270 emulator and zowe profile levels, we do’nt use RSE).
We use Windows-1252 encoding on Windows (not on Mac). 

For second message (rmdir of temporary folder), I already view it on two conditions:
- more than one instance of VS Code (and IBM Z Open Editor) active at the same time
- After ugrading of Z Open Editor and reload Windows on VS Code (probably not this case because path is related to 3.3.0 version of ZOE)

**Comment by ETHAN-MENDEL** [comment]
@YvesMichon could you post language server logs of the updated issue?
I think they could be different, but possibly related.

**Comment by FALLAI-Denis** [comment]
> Sorray I'm unable to reopen this issue. No button

Hi,
For your information, I got same problem after renewing zowe password:
![image](https://github.com/IBM/zopeneditor-about/assets/63861965/a05fbfed-c9ec-428a-aecd-5f1a920358e4)

**Comment by YvesMichon** [comment]
Hi @ETHAN-MENDEL 
The language server logs are in top of my update issue : 
```
[Error - 10:01:40] Request textDocument/documentLink failed. Error: Connection got disposed. at Object.dispose
(c:\Users\inemicy\.vscodeMoMaEQX\ibm.zopeneditor-3.3.0\dist\extension.js:8:1916445) at Object.dispose 
(c:\Users\inemicy\.vscodeMoMaEQX\ibm.zopeneditor-3.3.0\dist\extension.js:8:1980282) at 
c:\Users\inemicy\.vscodeMoMaEQX\ibm.zopeneditor-3.3.0\dist\extension.js:8:1976878 
```

**Comment by phaumer** [comment]
@YvesMichon our apologies. As the language server runs as a separate process they write their own logs. The logs get placed into a temp directory and the startup message in the Z Open Editor log tells you the location. See here for detailed instructions: <https://ibm.github.io/zopeneditor-about/Docs/locating_local_client_logs.html#locating-vs-code-extension-and-lsp-log-files-on-the-local-client>

**Comment by YvesMichon** [comment]
Hi @phaumer , @ETHAN-MENDEL 

Here is the logs.

IBM in DEBUG
[ibm.log](https://github.com/IBM/zopeneditor-about/files/13266694/ibm.log)

Language server
[ls.log](https://github.com/IBM/zopeneditor-about/files/13266698/ls.log)

**Comment by Peariforme** [comment]
Hello,

Some users have the same problem in my company and there is not special characters in the copy being retrieved

**Comment by PrasangAPrajapati** [comment]
@YvesMichon @Peariforme are you still seeing this error when editing your COBOL programs?

**Comment by sdaimwood** [comment]
Hi @YvesMichon @Peariforme, I'll be closing this item. If you see this problem again please create a new issue. Thank you for using Z Open Editor.
