### ISSUE TITLE
Internal Error Code: -32603 Request textDocument/documentSymbol failed

### ISSUE THREAD

**Issue by SG-A47** [IBM/zopeneditor-about#375]
Describe the bug
When I do a cut and paste in a HLASM-Source, this error is shown.

Steps to reproduce

    Double Click on a word
    CTRL-C cut it
    Double Click another word
    CTRL-V paste

Expected behavior
No error

Lines from the Error screen
[Error - 10:11:46] Request textDocument/documentSymbol failed.
Message: Internal error.
Code: -32603
java.util.concurrent.CompletionException: java.util.ConcurrentModificationException
at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.util.ConcurrentModificationException
at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
at com.ibm.wazi.lsp.hlasm.core.parser.AST.getSymbolInformation(AST.java:112)
at com.ibm.wazi.lsp.hlasm.core.handlers.DocumentSymbolHandler.getSymbols(DocumentSymbolHandler.java:33)
at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer.lambda$4(HLASMLanguageServer.java:217)
at com.ibm.wazi.lsp.hlasm.core.HLASMLanguageServer$$Lambda$124/0x00000000148e1140.apply(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
... 6 more

Environment (please complete the following information):
Version: 1.79.2 (user setup)
Commit: 695af097c7bd098fbf017ce3ac85e09bbc5dda06
Datum: 2023-06-14T08:57:04.379Z
Electron: 22.5.7
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
Betriebssystem: Windows_NT x64 10.0.22621
IBM Z Open Editor v3.3.1.

Additional context
You can ignore this error by closing the error window, but it rises again and again.

**Comment by sdaimwood** [comment]
I'm not able to reproduce this exact issue, although I am noticing other buggy behavior when copy and pasting rapidly. Could you provide some more information that will help diagnose?

- Approximate number of lines in code?
- Are you seeing this error when making rapid changes in the program other than copying and pasting? e.g. backspacing to remove a label name 
- Is macro resolution enabled? 
   - If not, is there any zowe explorer connection being used to retrieve COPY members?

**Comment by SG-A47** [comment]
Hi sdaimwood,

I can´t reproduce this error either. It is happening occasionally
The programs have about 4000 - 6000 lines.
Rapid changes aren' t a problem.
I use macro resolution and retrieve Copy-Members. Sometimes there are Copy-Members missing, but that should be no problem.
They are marked with a red wavy line and you get an error message in the problem windows.

**Comment by sdaimwood** [comment]
Hi @SG-A47, are you still seeing this error when editing your HLASM programs?

**Comment by sdaimwood** [comment]
I'm going to close this issue due to lack of activity and inability to reproduce, if you continue to see similar errors please reply here.
