### ISSUE TITLE
String index out of range

### ISSUE THREAD

**Issue by macjabeth** [IBM/zopeneditor-about#76]
## Development environment used

- Z Open Editor version: 1.0.3
- Editor Platform
  - [x] Visual Studio Code
  - [ ] CodeReady Workspaces
  - [ ] Eclipse Che
  - [ ] Standalone Theia
- Editor Platform Version: 1.48.2
- Operating System (on which VS Code runs such as Windows 10 2004, otherwise name and version of platform such as OpenShift v4.3): Windows 10 Enterprise Version 1909
- Java Version (when using VS Code or Theia, extecute `java -version` and paste the details here):
```
java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)
```
- [ ] Related to RSE API?
  - RSE API Plugin version:
  - Zowe CLI version:
  - Node.js version:
- Logs attached (see [here](https://ibm.github.io/zopeneditor-about/Docs/knownissues.html) how to get them): yes/no
```
[Error - 3:27:45 PM] Request textDocument/documentHighlight failed.
  Message: Internal error.
  Code: -32603 
java.util.concurrent.CompletionException: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:314)
	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:319)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:645)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837)
	at com.ibm.lsp.pl1.core.handlers.Validator.isIncludeFile(Validator.java:79)
	at com.ibm.lsp.pl1.core.handlers.DocumentHighlightHandler.computeOccurrences(DocumentHighlightHandler.java:54)
	at com.ibm.lsp.pl1.core.handlers.DocumentHighlightHandler.documentHighlight(DocumentHighlightHandler.java:90)
	at com.ibm.lsp.pl1.core.PL1LanguageServer.lambda$4(PL1LanguageServer.java:190)
	at com.ibm.lsp.pl1.core.PL1LanguageServer$1.apply(PL1LanguageServer.java:285)
	at com.ibm.lsp.pl1.core.PL1LanguageServer$1.apply(PL1LanguageServer.java:1)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	... 6 more
```

## Problem Description

I'm trying to work with a PL1 file and it throws an error any time I click or move the cursor on something. I don't have a Zowe profile set up / connected, I'm just working locally.

Detailed steps for reproducing the problem:

1. open scratchpad file
2. paste in PL1 code
2. set language to PL1
3. click or move the cursor on one of the variables

### Observed behavior

![image](https://user-images.githubusercontent.com/8473052/91220060-9b919800-e6e9-11ea-86c2-635e9281f1b4.png)

### Expected behavior

No errors popping up.

**Comment by gplambert** [comment]
@macjabeth -  if you create a file with an extension of `.pli`, then paste in your code, do you still have the issue?

What is the file extension of the scratchpad file you opened?

Just checking to see if it is a file association issue.  Thanks

**Comment by macjabeth** [comment]
> @macjabeth - if you create a file with an extension of `.pli`, then paste in your code, do you still have the issue?
> 
> What is the file extension of the scratchpad file you opened?
> 
> Just checking to see if it is a file association issue. Thanks

Interesting. The file I was working with had no extension - I changed it manually when opening it.

When I created a new file with `.pli` extension it worked! I also looked directly into the settings and took out all the file associates / reloaded VSCode.

**Comment by phaumer** [comment]
@macjabeth thanks a lot for letting us know. I will close this item for now. Feel free to reopen it if there is still a problem.
Internally, we created an item to fix that exception that you have seen. Those should not happen.

**Comment by NickStrupat** [comment]
I am also getting this exception, but for COBOL files that don't have an extension. Possibly the same issue.

**Comment by phaumer** [comment]
@NickStrupat thanks. We have a fix for this. It will in our next release.
